apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  namespace: traefik
spec:
  rules:
  - host: traefik.tfriver.sandbox.cvpcorp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-service
            port:
              number: 9000

