#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$PGUSER" --dbname "$PGDATABASE" <<-EOSQL
  CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
  CREATE SCHEMA keycloak AUTHORIZATION $KEYCLOAK_DB_USER;
  CREATE USER $NEXTAUTH_DB_USER WITH PASSWORD '$NEXTAUTH_DB_PASSWORD';
  CREATE SCHEMA nextauth AUTHORIZATION $NEXTAUTH_DB_USER;
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
  CREATE SCHEMA app AUTHORIZATION $APP_DB_USER;
EOSQL
